language: rust

rust:
  - stable
  - beta
  - nightly

cache: cargo

install:
  - rustup default nightly
  - sudo apt-get install gcc-arm-none-eabi
  - rustup target add thumbv7em-none-eabihf

script:
  - make ci